default-root-container-layout = 'accordion'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[mode.main.binding]
    alt-slash = 'layout h_tiles h_accordion'

    alt-j = 'focus --boundaries-action wrap-around-the-workspace left'
    alt-k = 'focus --boundaries-action wrap-around-the-workspace right'

    alt-shift-j = 'move left'
    alt-shift-k = 'move right'

    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-6 = 'workspace 6'
    alt-7 = 'workspace 7'
    alt-8 = 'workspace 8'
    alt-9 = 'workspace 9'

    alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

    alt-shift-r = 'reload-config'
